export DATA_GENERATOR_DB=retaildw
export DATA_GENERATOR_HOST=172.18.0.1
export DATA_GENERATOR_PORT=5432
export DATA_GENERATOR_USER=user1
export DATA_GENERATOR_PASSWORD=user1
export DATA_GENERATOR_SCHEMA=generator

export E_COMMERCE_DB=retaildw
export E_COMMERCE_HOST=172.18.0.1
export E_COMMERCE_PORT=5432
export E_COMMERCE_USER=user1
export E_COMMERCE_PASSWORD=user1
export E_COMMERCE_SCHEMA=ecommerce

export WAREHOUSE_DB=retaildw
export WAREHOUSE_HOST=172.18.0.1
export WAREHOUSE_PORT=3306
export WAREHOUSE_USER=user1
export WAREHOUSE_PASSWORD=user1

export WIDGETS_HOME=~/open-ended-capstone/
export WIDGETS_LOG_DIR=$WIDGETS_HOME/logs
export WIDGETS_LOG_CONF=$WIDGETS_HOME/logging.conf

