version: "2"
services:
  sourcesystems:
    build:
      context: .
      dockerfile: Dockerfile-sourcesystems
          
networks: 
    default:
        external:
            name: widgets-unlimited-network
            