FROM python:3.8-slim

ADD ./requirements-sourcesystems.txt ./
RUN pip install -r requirements-sourcesystems.txt

COPY WidgetsUnlimited/ WidgetsUnlimited/

ENTRYPOINT ["python", "WidgetsUnlimited/demo1.py"]
