FROM python:3.8-slim

ADD ./requirements-operations.txt ./
RUN pip install -r requirements-operations.txt

COPY WidgetsUnlimited/ WidgetsUnlimited/

ENTRYPOINT ["python", "WidgetsUnlimited/demo1.py"]
